set file and dir permissions
status-im/nimbus-eth2 pull request #1922
Opened 2020-10-30 00:46 UTC by stefantalpalaru

- get rid of group read and write permissions for directories; there is no justification for allowing that
- set the desired permissions instead of exiting the program - fixes https://github.com/status-im/nimbus-eth2/issues/1921
- don't call the POSIX `acess()` function, since it doesn't do anything we need. https://man7.org/linux/man-pages/man2/access.2.html :

`In other words, access() does not answer the "can I read/write/execute this file?" question.  It answers a slightly different
question: "(assuming I'm a setuid binary) can the user who invoked me read/write/execute this file?", which gives set-user-ID
programs the possibility to prevent malicious users from causing them to read files which users shouldn't be able to read.`

2020-10-30 08:24 UTC, cheatfate requested changes
This PR should not be merged until discussion in https://github.com/status-im/nimbus-eth2/issues/1921 will not be finished.

2020-11-13 13:25 UTC, zah commented
I support merging this and including it in the next 0.6.x release. Couple of weeks later, it should be followed by a PR going back to the more strict handling advocated by @cheatfate which should be our long-term policy.

2020-11-13 15:37 UTC, arnetheduck commented
not sure this is meaningful any more - ie the damage is done already

2020-11-14 17:11 UTC, zah commented
This is a new more minor change to the permissions (but still breaking). It removes the group-level access from the sensitive directories.

2020-11-17 21:28 UTC, merged

2020-11-30 17:39 UTC, cheatfate commented
@zah couple of weeks already passed but there no new PR, so maybe i should open "security" issues because of that?

2020-11-30 17:41 UTC, zah commented
Yes, I think it's time that we fix this. Perhaps it can be addressed in the not yet merged passwordless keystores branch?

2020-11-30 17:48 UTC, cheatfate commented
@zah i have created new issue https://github.com/status-im/nimbus-eth2/issues/2115